MvcProjeKampi/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ContactController : Controller
    {
        ContactManager cm = new ContactManager(new EfContactDal());
        MessageManager mm = new MessageManager(new EfMessageDal());
        ContactValidator cv = new ContactValidator();
        public ActionResult Index()
        {
            var contactValues = cm.GetList();
            return View(contactValues);
        }
        public ActionResult GetContactDetail(int id)
        {
            var contactValue = cm.GetById(id);
            contactValue.Read = true;
            cm.ContactUpdate(contactValue);
            return View(contactValue);
        }
        public PartialViewResult LeftMenuPartial()
        {
            //var contactMessageNumber = cm.GetList().Count().ToString();
            //ViewBag.cmc = contactMessageNumber;

            //var inboxNumber = mm.GetListInbox().Count.ToString();
            //ViewBag.inn = inboxNumber;

            //var sendboxNumber = mm.GetListSendbox().Count().ToString();
            //ViewBag.sn = sendboxNumber;

            //var draftnumber = mm.GetListDraft().Count().ToString();
            //ViewBag.dn = draftnumber;

            //var trashnumber = mm.GetListTrash().Count().ToString();
            //ViewBag.tn = trashnumber;

            var p = (string)Session["AdminUserName"];
            var unRead = mm.GetUnReadMessageForInbox(p).Count().ToString();
            ViewBag.unr = unRead;

            var unReadContact = cm.GetUnReadMessageForContact().Count().ToString();
            ViewBag.unrc = unReadContact;
            return PartialView();
        }
        public ActionResult Delete(int id)
        {
            var contact = cm.GetById(id);
            cm.ContactFullyDelete(contact);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class MessageController : Controller
    {
        MessageManager mm = new MessageManager(new EfMessageDal());
        MessageValidator messagevalidator = new MessageValidator();
        public ActionResult Inbox()
        {
            var p = (string)Session["AdminUserName"];
            var messageList = mm.GetListInbox(p);
            return View(messageList);
        }
        public ActionResult GetInboxMessageDetail(int id)
        {
            var messageValue = mm.GetById(id);
            messageValue.Read = true;
            mm.MessageUpdate(messageValue);
            return View(messageValue);
        }
        public ActionResult Sendbox()
        {
            var p = (string)Session["AdminUserName"];
            var messageList = mm.GetListSendbox(p);
            return View(messageList);
        }
        public ActionResult GetSendboxMessageDetail(int id)
        {
            var messageValue = mm.GetById(id);
            return View(messageValue);
        }
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
        public class MultipleButtonAttribute : ActionNameSelectorAttribute
        {
            public string Name { get; set; }
            public string Argument { get; set; }

            public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
            {
                var isValidName = false;
                var keyValue = string.Format("{0}:{1}", Name, Argument);
                var value = controllerContext.Controller.ValueProvider.GetValue(keyValue);

                if (value != null)
                {
                    controllerContext.Controller.ControllerContext.RouteData.Values[Name] = Argument;
                    isValidName = true;
                }

                return isValidName;
            }
        }
        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "NewMessage")]
        [ValidateInput(false)]
        public ActionResult NewMessage(Message message)
        {
            var sender = (string)Session["AdminUserName"];
            ValidationResult results = messagevalidator.Validate(message);
            if (results.IsValid)
            {
                message.SenderMail = sender;
                message.SenderStatus = true;
                message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                mm.MessageAdd(message);
                return RedirectToAction("Sendbox");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult GetMessageDetail(int id)
        {
            var messageValue = mm.GetById(id);
            return View(messageValue);
        }
        public ActionResult GetListDraft()
        {
            var p = (string)Session["AdminUserName"];
            var draftList = mm.GetListDraft(p);
            return View(draftList);
        }
        public ActionResult GetDraftMessageDetail(int id)
        {
            var messageValue = mm.GetById(id);
            return View(messageValue);
        }
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "SaveDraft")]
        [ValidateInput(false)]
        public ActionResult SaveDraft(Message msg)
        {
            var sender = (string)Session["AdminUserName"];
            msg.Draft = true;
            msg.SenderStatus = true;
            msg.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            msg.SenderMail = sender;          
            mm.MessageAdd(msg);
            return RedirectToAction("GetListDraft");
        }
        public ActionResult TrashList()
        {
            var p = (string)Session["AdminUserName"];
            var trash = mm.GetListTrash(p);
            return View(trash);
        }
        public ActionResult MakePassive(int id)
        {
            var p = (string)Session["AdminUserName"];
            var message = mm.GetById(id);
            if (message.ReceiverMail == p)
            {
                message.ReceiverStatus = true;
            }
            else if (message.SenderMail == p)
            {
                message.SenderStatus = false;
            }
            mm.MessageDelete(message);
            return RedirectToAction("TrashList");
        }
        public ActionResult Delete(int id)
        {
            var message = mm.GetById(id);
            message.ReceiverDelete = true;
            mm.MessageFullyDelete(message);
            return RedirectToAction("TrashList");
        }
        public ActionResult TrashDetails(int id)
        {
            var messageValue = mm.GetById(id);
            return View(messageValue);
        }
    }
}

MvcProjeKampi/Views/Message/GetDraftMessageDetail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetDraftMessageDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Mesaj Detayları</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">    
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mesaj</h3>
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.Subject</h5>
                            <br />
                            <h6>
                                Alıcı: @Model.ReceiverMail
                                <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd/MMMM/yyy")</span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            <p>@Html.Raw(Model.MessageContent)</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            <a href="/Message/NewMessage" class="btn btn-default"><i class="fas fa-reply"></i> Reply</a>
                            <a href="/Message/MakePassive/@Model.MessageId" class="btn btn-default"><i class="far fa-trash-alt"></i> Delete</a>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/GetInboxMessageDetail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetInboxMessageDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Mesaj Detayları</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">   
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mesaj</h3>                       
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.Subject</h5>
                            <br />
                            <h6>
                               Gönderici: @Model.SenderMail
                                <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd/MMMM/yyy")</span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            <p>@Html.Raw(Model.MessageContent)</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            <a href="/Message/NewMessage" class="btn btn-default"><i class="fas fa-reply"></i> Reply</a>
                            <a href="/Message/MakePassive/@Model.MessageId" class="btn btn-default"><i class="far fa-trash-alt"></i> Delete</a>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/GetListDraft.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "GetListDraft";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Taslaklar Kutusu</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">   
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Taslaklar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="mailbox-star"><a href="/Message/MakePassive/@item.MessageId"><i class="fas fa-trash text-danger"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetDraftMessageDetail/@item.MessageId">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b>
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@item.MessageDate.ToString("dd/MMMMMMM/yyyy")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>                   
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/GetMessageDetail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetMessageDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Mesaj Detayları</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">   
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mesaj</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.Subject</h5>
                            <br />
                            <h6>
                                @if (Model.ReceiverMail == "admin@gmail.com")
                                {
                                    <a>Mail:</a> @Model.SenderMail
                                }
                                else
                                {
                                    <a>Mail:</a> @Model.ReceiverMail
                                }
                                <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd/MMMM/yyy")</span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            <p>@Html.Raw(Model.MessageContent)</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            <button type="button" class="btn btn-default"><i class="fas fa-reply"></i> Reply</button>
                            <button type="button" class="btn btn-default"><i class="fas fa-share"></i> Forward</button>
                        </div>
                        <button type="button" class="btn btn-default"><i class="far fa-trash-alt"></i> Delete</button>
                        <button type="button" class="btn btn-default"><i class="fas fa-print"></i> Print</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/GetSendboxMessageDetail.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetSendboxMessageDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Mesaj Detayları</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">   
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mesaj</h3>                     
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.Subject</h5>
                            <br />
                            <h6>
                              Alıcı: @Model.ReceiverMail
                                <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd/MMMM/yyy")</span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            <p>@Html.Raw(Model.MessageContent)</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            <a href="/Message/NewMessage" class="btn btn-default"><i class="fas fa-reply"></i> Reply</a>
                            <a href="/Message/MakePassive/@Model.MessageId" class="btn btn-default"><i class="far fa-trash-alt"></i> Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Gelen Kutusu</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">  
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-0">                       
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="mailbox-star"><a href="/Message/MakePassive/@item.MessageId"><i class="fas fa-trash text-danger"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetInboxMessageDetail/@item.MessageId">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b>

                                            </td>
                                            @if (item.Read == false)
                                            {
                                                <td><i style="color:red" class="fas fa-fire"></i></td>
                                            }
                                            else
                                            {
                                                <td><i class="fas fa-fire"></i></td>
                                            }
                                            <td class="mailbox-date">@item.MessageDate.ToString("dd/MMM/yyyy")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/NewMessage.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Yeni Mesaj Sayfası</h3>
<br />
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Themes/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
    <script src="~/Themes/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">   
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                @using (Html.BeginForm("", "Message", FormMethod.Post))
                {
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                        </div>
                        <div class="card-body">
                            @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control", @placeholder = "Alıcı" })
                            @Html.ValidationMessageFor(x => x.ReceiverMail, "", new { @style = "color:red" })
                            <br />
                            @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @placeholder = "Konu" })
                            @Html.ValidationMessageFor(x => x.Subject, "", new { @style = "color:red" })
                            <br />
                            <div class="form-group">
                                <textarea name="MessageContent" id="compose-textarea" class="form-control" style="height: 300px" placeholder="Mesajınız">                                           
                            </textarea>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="float-right">
                                <button type="submit" class="btn btn-default" name="action:SaveDraft"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                <button type="submit" class="btn btn-primary" name="action:NewMessage"><i class="far fa-envelope"></i> Gönder</button>
                            </div>
                            <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
    <script src="~/Themes/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/Themes/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <script>
        $(function () {
            $('#compose-textarea').summernote()
        })
    </script>
</body>
</html>

MvcProjeKampi/Views/Message/Sendbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Sendbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Gönderilen Kutusu</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gönderilen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="mailbox-star"><a href="/Message/MakePassive/@item.MessageId"><i class="fas fa-trash text-danger"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetSendboxMessageDetail/@item.MessageId">@item.ReceiverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> 
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@item.MessageDate.ToString("dd/MMMMMMM/yyyy")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/TrashDetails.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "TrashDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>Mesaj Detayları</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">    
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "Contact")
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mesaj</h3>                       
                    </div>
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.Subject</h5>
                            <br />
                            <h6>
                                Mail:
                                @if (Model.SenderMail == (string)Session["AdminUserName"])
                                {
                                    @Model.ReceiverMail
                                }
                                else
                                {
                                    @Model.SenderMail
                                }
                                <span class="mailbox-read-time float-right">@Model.MessageDate.ToString("dd/MMMM/yyy")</span>
                            </h6>
                        </div>
                        <div class="mailbox-read-message">
                            <p>@Html.Raw(Model.MessageContent)</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-right">
                            <a href="/Message/NewMessage" class="btn btn-default"><i class="fas fa-reply"></i> Reply</a>
                            <a href="/Message/Delete/@Model.MessageId" class="btn btn-default"><i class="far fa-trash-alt"></i> Delete</a>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>