MvcProjeKampi/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        Context c = new Context();
        public ActionResult WriterContent(string p)
        {          
            p = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterId).FirstOrDefault();
            var contents = cm.GetListByWriter(writerIdInfo);
            return View(contents);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            var baslik = hm.GetById(id);
            ViewBag.b = baslik.HeadingName;
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content content)
        {          
            string mail = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterId).FirstOrDefault();
            content.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            content.WriterId = writerIdInfo;
            content.ContentStatus = true;
            cm.ContentAdd(content);
            return RedirectToAction("WriterContent");
        }
    }
}

MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<br />
<h1>@ViewBag.b</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingId" value="@ViewBag.d"/>
        @Html.Label("İçerik")
        @Html.TextAreaFor(x => x.ContentValue, 10, 30, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary"><i class="fas fa-plus"></i> Ekle</button>
        <a href="/WriterPanel/AllHeading" class="btn btn-warning"><i class="fas fa-backward"></i> Geri Dön</a>
    </div>
}

MvcProjeKampi/Views/WriterPanelContent/WriterContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "WriterContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<br />
<h3>Yazılarım</h3>
<br />
<html>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@item.ContentDate.ToString("dd/MMM/yyyy")</span>
                                </div>
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="/Writer/Index">@item.Writer.WriterName @item.Writer.WriterSurname (@item.Heading.HeadingName)</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>