MvcProjeKampi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index(int page = 1)
        {
            var aboutValues = abm.GetList().ToPagedList(page, 10);
            return View(aboutValues);
        }
        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAbout(About about)
        {
            abm.AboutAdd(about);
            return RedirectToAction("Index");
        }
        public PartialViewResult AddAboutPartial()
        {
            return PartialView();
        }
        public ActionResult ChangeStatus(int id)
        {
            var about = abm.GetById(id);
            if (about.Status == false)
            {
                about.Status = true;
            }
            else
            {
                about.Status = false;
            }
            abm.AboutDelete(about);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/About/AddAboutPartial.cshtml
<button class="btn btn-primary"  style="margin-left:25px;position:absolute;right:10px" data-toggle="modal" data-target="#Modal1">
    <i class="fas fa-plus"></i> Ekle
</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Metin Girişi</h2>
            </div>
            <form method="post" action="/About/AddAbout">
                <div class="modal-body">
                    <label>Başlık</label>
                    <input type="text" name="AboutDetails1" class="form-control" />
                    <br />
                    <label>Açıklama</label>
                    <input type="text" name="AboutDetails2" class="form-control" />
                    <br />
                    <label>Görsel 1</label>
                    <input type="text" name="AboutImage1" class="form-control" />
                    <br />
                    <label>Görsel 2</label>
                    <input type="text" name="AboutImage2" class="form-control" />
                    <br />
                    <button class="btn btn-primary"><i class="fas fa-plus"></i> Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>

MvcProjeKampi/Views/About/Index.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h3>
    Hakkımızda
    @Html.Action("AddAboutPartial", "About")
</h3>
<br />
<table class="table table-bordered table-hover">
    <tr>
        <th>Başlık</th>
        <th>Açıklama</th>
        <th>Durum</th>
        <th>İşlemler</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AboutDetails1</td>
            <td>@item.AboutDetails2</td>
            <td>
                @if (item.Status == true)
                {
                    <p style="color:green">Aktif</p>
                }
                else
                {
                    <p style="color:red">Pasif</p>
                }
            </td>
            @if (item.Status == true)
            {
                <td><a class="btn btn-danger btn-sm" href="/About/ChangeStatus/@item.AboutId"><i class="fas fa-times-circle"></i> Pasif Yap</a></td>
            }
            else
            {
                <td><a class="btn btn-success btn-sm" href="/About/ChangeStatus/@item.AboutId"><i class="fas fa-check"></i> Aktif Yap</a></td>
            }

        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
{
    LiElementClasses = new List<string>
    {
        "page-link"
    }
})