MvcProjeKampi/Controllers/ChartController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using MvcProjeKampi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ChartController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CategoryChart()
        {
            return Json(BlogList(), JsonRequestBehavior.AllowGet);
        }
        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> ct = new List<CategoryClass>();
            ct.Add(new CategoryClass()
            {
                CategoryName = "Yazılım",
                CategoryCount = 8
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Seyehat",
                CategoryCount = 12
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Spor",
                CategoryCount = 50
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Teknoloji",
                CategoryCount = 2
            });
            return ct;
        }
        public ActionResult PieChart()
        {
            return View();
        }
        public ActionResult WriterHeadingChart()
        {
            return Json(WriterHeadingList(), JsonRequestBehavior.AllowGet);
        }
        public List<WritersHeadingsCount> WriterHeadingList()
        {
            List<WritersHeadingsCount> whc = new List<WritersHeadingsCount>();
            using (var c = new Context())
            {
                whc = c.Writers.Select(x => new WritersHeadingsCount
                {
                    WriterName = x.WriterName  + " " +  x.WriterSurname,
                    HeadingCount = x.Headings.Count()
                }).ToList();
            }
            return whc;
        }
        public ActionResult LineChart()
        {
            return View();
        }
        public ActionResult CategoriesHeadingChart()
        {
            return Json(CategoriesHeadingList(), JsonRequestBehavior.AllowGet);
        }
        public List<CategoriesHeadingsCount> CategoriesHeadingList()
        {
            List<CategoriesHeadingsCount> chc = new List<CategoriesHeadingsCount>();
            using (var c= new Context())
            {
                chc = c.Categories.Select(x => new CategoriesHeadingsCount
                {
                    CategoryName = x.CategoryName,
                    HeadingCount = x.Headings.Count()
                }).ToList();
            }
            return chc;
        }
        public ActionResult ColumnChart()
        {
            return View();
        }
        public ActionResult HeadingsContentChart()
        {
            return Json(HeadingsContentList(), JsonRequestBehavior.AllowGet);
        }
        public List<HeadingsContentCount> HeadingsContentList()
        {
            List<HeadingsContentCount> hcc = new List<HeadingsContentCount>();
            using (var c = new Context())
            {
                hcc = c.Headings.Select(x => new HeadingsContentCount
                {
                    HeadingName = x.HeadingName,
                    ContentCount = x.Contents.Count()
                }).ToList();
            }
            return hcc;
        }
    }
}

MvcProjeKampi/Views/Chart/ColumnChart.cshtml
@{
    ViewBag.Title = "ColumnChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("HeadingsContentChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'HeadingName');
            data.addColumn('number', 'ContentCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.HeadingName, obj.ContentCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Başlık - İçerik Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'CategoryCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Kategori - Başlık Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/LineChart.cshtml
@{
    ViewBag.Title = "LineChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoriesHeadingChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'HeadingCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.HeadingCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Kategori - Başlık Grafiği",
                width: 1000,
                height: 800,    
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/PieChart.cshtml
@{
    ViewBag.Title = "PieChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("WriterHeadingChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'WriterName');
            data.addColumn('number', 'HeadingCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.WriterName, obj.HeadingCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Yazar - Başlık Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>